---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 1h0m0s
  targetNamespace: istio-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace