---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: observability
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  interval: 1h0m0s
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    grafana:
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-kube-prometheus-prometheus.observability:9090/
              access: proxy
              isDefault: true
            - name: Loki
              type: loki
              url: http://loki.observability:3100
              access: proxy
            - name: Tempo
              type: tempo
              url: http://tempo-tempo-distributed-querier.observability:3100
              access: proxy